// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson917759c2DecodeGithubComWrestler094ShortenerInternalDto(in *jlexer.Lexer, out *BatchResponseList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(BatchResponseList, 0, 2)
			} else {
				*out = BatchResponseList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 BatchResponseItem
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson917759c2EncodeGithubComWrestler094ShortenerInternalDto(out *jwriter.Writer, in BatchResponseList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v BatchResponseList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson917759c2EncodeGithubComWrestler094ShortenerInternalDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BatchResponseList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson917759c2EncodeGithubComWrestler094ShortenerInternalDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BatchResponseList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson917759c2DecodeGithubComWrestler094ShortenerInternalDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BatchResponseList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson917759c2DecodeGithubComWrestler094ShortenerInternalDto(l, v)
}
func easyjson917759c2DecodeGithubComWrestler094ShortenerInternalDto1(in *jlexer.Lexer, out *BatchResponseItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "correlation_id":
			out.CorrelationID = string(in.String())
		case "short_url":
			out.ShortURL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson917759c2EncodeGithubComWrestler094ShortenerInternalDto1(out *jwriter.Writer, in BatchResponseItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"correlation_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.CorrelationID))
	}
	{
		const prefix string = ",\"short_url\":"
		out.RawString(prefix)
		out.String(string(in.ShortURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BatchResponseItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson917759c2EncodeGithubComWrestler094ShortenerInternalDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BatchResponseItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson917759c2EncodeGithubComWrestler094ShortenerInternalDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BatchResponseItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson917759c2DecodeGithubComWrestler094ShortenerInternalDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BatchResponseItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson917759c2DecodeGithubComWrestler094ShortenerInternalDto1(l, v)
}
func easyjson917759c2DecodeGithubComWrestler094ShortenerInternalDto2(in *jlexer.Lexer, out *BatchRequestList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(BatchRequestList, 0, 2)
			} else {
				*out = BatchRequestList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v4 BatchRequestItem
			(v4).UnmarshalEasyJSON(in)
			*out = append(*out, v4)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson917759c2EncodeGithubComWrestler094ShortenerInternalDto2(out *jwriter.Writer, in BatchRequestList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v5, v6 := range in {
			if v5 > 0 {
				out.RawByte(',')
			}
			(v6).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v BatchRequestList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson917759c2EncodeGithubComWrestler094ShortenerInternalDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BatchRequestList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson917759c2EncodeGithubComWrestler094ShortenerInternalDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BatchRequestList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson917759c2DecodeGithubComWrestler094ShortenerInternalDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BatchRequestList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson917759c2DecodeGithubComWrestler094ShortenerInternalDto2(l, v)
}
func easyjson917759c2DecodeGithubComWrestler094ShortenerInternalDto3(in *jlexer.Lexer, out *BatchRequestItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "correlation_id":
			out.CorrelationID = string(in.String())
		case "original_url":
			out.OriginalURL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson917759c2EncodeGithubComWrestler094ShortenerInternalDto3(out *jwriter.Writer, in BatchRequestItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"correlation_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.CorrelationID))
	}
	{
		const prefix string = ",\"original_url\":"
		out.RawString(prefix)
		out.String(string(in.OriginalURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BatchRequestItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson917759c2EncodeGithubComWrestler094ShortenerInternalDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BatchRequestItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson917759c2EncodeGithubComWrestler094ShortenerInternalDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BatchRequestItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson917759c2DecodeGithubComWrestler094ShortenerInternalDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BatchRequestItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson917759c2DecodeGithubComWrestler094ShortenerInternalDto3(l, v)
}
