// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package handlers

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (ShortenRequest) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ShortenRequest) UnmarshalJSON([]byte) error        { return nil }
func (ShortenRequest) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ShortenRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ShortenRequest *ShortenRequest

func (ShortenResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ShortenResponse) UnmarshalJSON([]byte) error        { return nil }
func (ShortenResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ShortenResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ShortenResponse *ShortenResponse

func (URLHandler) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*URLHandler) UnmarshalJSON([]byte) error        { return nil }
func (URLHandler) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*URLHandler) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_URLHandler *URLHandler
