definitions:
  dto.BatchRequestItem:
    properties:
      correlation_id:
        description: Идентификатор корреляции для связи запроса и ответа
        type: string
      original_url:
        description: Оригинальный URL для сокращения
        type: string
    type: object
  dto.BatchResponseItem:
    properties:
      correlation_id:
        description: Идентификатор корреляции из запроса
        type: string
      short_url:
        description: Сокращенный URL
        type: string
    type: object
  dto.UserURLItem:
    properties:
      original_url:
        description: Оригинальный URL
        type: string
      short_url:
        description: Сокращенный URL
        type: string
    type: object
  handlers.ShortenRequest:
    properties:
      url:
        description: URL для сокращения
        example: https://example.com
        type: string
    type: object
  handlers.ShortenResponse:
    properties:
      result:
        description: Сокращенный URL
        example: http://localhost:8080/abc123
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    post:
      consumes:
      - text/plain
      description: Сохраняет URL и возвращает его сокращенную версию
      parameters:
      - description: URL для сокращения
        in: body
        name: url
        required: true
        schema:
          type: string
      produces:
      - text/plain
      responses:
        "201":
          description: Сокращенный URL
          schema:
            type: string
        "400":
          description: Неверный формат запроса
          schema:
            type: string
        "409":
          description: Сокращенный URL
          schema:
            type: string
      summary: Сохранить URL в текстовом формате
      tags:
      - URL
  /{id}:
    get:
      description: Перенаправляет на оригинальный URL по сокращенному идентификатору
      parameters:
      - description: Идентификатор сокращенного URL
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "307":
          description: Редирект на оригинальный URL
          schema:
            type: string
        "400":
          description: Неверный формат запроса
          schema:
            type: string
        "410":
          description: URL был удален
          schema:
            type: string
      summary: Получить оригинальный URL
      tags:
      - URL
  /api/shorten:
    post:
      consumes:
      - application/json
      description: Сохраняет URL и возвращает его сокращенную версию
      parameters:
      - description: URL для сокращения
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.ShortenRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.ShortenResponse'
        "400":
          description: Неверный формат запроса
          schema:
            type: string
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handlers.ShortenResponse'
      summary: Сохранить URL в формате JSON
      tags:
      - URL
  /api/shorten/batch:
    post:
      consumes:
      - application/json
      description: Сохраняет массив URL и возвращает массив сокращенных URL
      parameters:
      - description: Массив URL для сокращения
        in: body
        name: batch
        required: true
        schema:
          items:
            $ref: '#/definitions/dto.BatchRequestItem'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/dto.BatchResponseItem'
            type: array
        "400":
          description: Неверный формат запроса
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Пакетное сохранение URL
      tags:
      - URL
  /api/user/urls:
    delete:
      consumes:
      - application/json
      description: Удаляет указанные URL пользователя
      parameters:
      - description: Массив идентификаторов URL для удаления
        in: body
        name: urls
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - text/plain
      responses:
        "202":
          description: Запрос на удаление принят
        "400":
          description: Неверный формат запроса
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Удалить URL пользователя
      tags:
      - URL
    get:
      description: Возвращает список всех URL, созданных пользователем
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.UserURLItem'
            type: array
        "204":
          description: Нет сохраненных URL
        "401":
          description: Пользователь не авторизован
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Получить все URL пользователя
      tags:
      - URL
swagger: "2.0"
